name: dynamic_logger
description: A simple and structured logger for Dart applications.
version: 0.1.1
homepage: https://github.com/CaoGiaHieu-dev/dynamic_logger
repository: https://github.com/CaoGiaHieu-dev/dynamic_logger
issue_tracker: https://github.com/CaoGiaHieu-dev/dynamic_logger/issues
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  logging: ^1.3.0
  dio: ^5.7.0
  collection: ^1.19.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

# Example files
example:
  - example/dynamic_logger_example.dart

# Exclude unnecessary files from the package
exclude:
  - example/**

# Add a license
license: MIT
