name: dynamic_logger
description: A simple and structured logger for Dart applications.
version: 0.4.0
homepage: https://github.com/CaoGiaHieu-dev/dynamic_logger
repository: https://github.com/CaoGiaHieu-dev/dynamic_logger
issue_tracker: https://github.com/CaoGiaHieu-dev/dynamic_logger/issues
environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ">5.0.0"
  test: ^1.24.0

# Example files
example:
  - example/dynamic_logger_example.dart

# Exclude unnecessary files from the package
exclude:
  - example/**

# Add a license
license: MIT
